/**
 * [ candy-e ] — ACTIONS D'AUDIT RGPD
 * Fichier : services/audit/audit.actions.js
 *
 * Convention de nommage alignée sur l'existant (routes/auth.js: 'LOGIN',
 * 'LOGOUT' ; routes/insi.js: 'INSI_RECUPERER') plutôt que sur le style
 * pointé ('auth.login.success') d'un référentiel générique — MAJUSCULES_
 * SNAKE_CASE, préfixées par la ressource concernée pour rester lisibles
 * dans le tableau de bord DPO. N'introduit pas de nouvelle convention.
 *
 * Limité aux ressources et actions qui existent réellement dans ce dépôt
 * (residents, consultations, ordonnances, traitements, transmissions,
 * notes_suivi, chutes, tournees_soins, soins_pansements, agenda, profiles,
 * identites/INSi) — pas de DMP/MSSanté/2FA/api_key/ehpad, absents du
 * périmètre actuel.
 */

'use strict';

const AUDIT_ACTIONS = Object.freeze({
  // AUTHENTIFICATION (déjà utilisées telles quelles par routes/auth.js)
  AUTH_LOGIN_SUCCESS: 'LOGIN',
  AUTH_LOGIN_FAILURE: 'LOGIN_FAILURE',
  AUTH_LOGOUT: 'LOGOUT',
  AUTH_PASSWORD_CHANGE: 'PASSWORD_CHANGE',
  AUTH_PASSWORD_RESET_REQUEST: 'PASSWORD_RESET_REQUEST',

  // COMPTES UTILISATEURS (profiles)
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_DELETED: 'USER_DELETED',
  USER_ROLE_CHANGED: 'USER_ROLE_CHANGED',
  USER_ACTIVATED: 'USER_ACTIVATED',
  USER_DEACTIVATED: 'USER_DEACTIVATED',

  // DOSSIER RÉSIDENT (données de santé — Art. 9 RGPD)
  RESIDENT_CREATED: 'RESIDENT_CREATED',
  RESIDENT_VIEWED: 'RESIDENT_VIEWED',
  RESIDENT_UPDATED: 'RESIDENT_UPDATED',
  RESIDENT_DELETED: 'RESIDENT_DELETED',
  RESIDENT_EXPORTED: 'RESIDENT_EXPORTED',
  RESIDENT_ARCHIVED: 'RESIDENT_ARCHIVED',

  // IDENTITÉ NATIONALE DE SANTÉ (INSi — déjà journalisé via INSI_<OP> dans routes/insi.js)
  RESIDENT_INS_QUALIFIED: 'INSI_QUALIFIER',
  RESIDENT_INS_QUERY: 'INSI_RECUPERER',

  // SOINS ET TRANSMISSIONS (données de santé)
  CONSTANTE_CREATED: 'CONSTANTE_CREATED',
  CONSTANTE_UPDATED: 'CONSTANTE_UPDATED',
  CONSULTATION_CREATED: 'CONSULTATION_CREATED',
  CONSULTATION_UPDATED: 'CONSULTATION_UPDATED',
  ORDONNANCE_CREATED: 'ORDONNANCE_CREATED',
  ORDONNANCE_UPDATED: 'ORDONNANCE_UPDATED',
  TRAITEMENT_CREATED: 'TRAITEMENT_CREATED',
  TRAITEMENT_UPDATED: 'TRAITEMENT_UPDATED',
  TRANSMISSION_CREATED: 'TRANSMISSION_CREATED',
  TRANSMISSION_UPDATED: 'TRANSMISSION_UPDATED',
  NOTE_SUIVI_CREATED: 'NOTE_SUIVI_CREATED',
  NOTE_SUIVI_UPDATED: 'NOTE_SUIVI_UPDATED',
  SOIN_CREATED: 'SOIN_CREATED',
  CHUTE_DECLAREE: 'CHUTE_DECLAREE',
  CHUTE_UPDATED: 'CHUTE_UPDATED',
  TOURNEE_CREATED: 'TOURNEE_CREATED',
  TOURNEE_UPDATED: 'TOURNEE_UPDATED',
  AGENDA_CREATED: 'AGENDA_CREATED',
  AGENDA_UPDATED: 'AGENDA_UPDATED',
  AGENDA_DELETED: 'AGENDA_DELETED',

  // REGISTRE DES TRAITEMENTS (Art. 30)
  REGISTRE_UPDATED: 'REGISTRE_UPDATED',

  // DROITS RGPD (Art. 15-22)
  RGPD_ACCESS_REQUEST: 'RGPD_ACCESS_REQUEST',
  RGPD_RECTIFICATION_REQUEST: 'RGPD_RECTIFICATION_REQUEST',
  RGPD_ERASURE_REQUEST: 'RGPD_ERASURE_REQUEST',
  RGPD_PORTABILITY_REQUEST: 'RGPD_PORTABILITY_REQUEST',
  RGPD_EXPORT_GENERATED: 'RGPD_EXPORT_GENERATED',
  RGPD_BREACH_DECLARED: 'RGPD_BREACH_DECLARED',

  // PURGE (Art. 5(1)(e) RGPD)
  PURGE_SCHEDULED: 'PURGE_SCHEDULED',
  PURGE_EXECUTED: 'PURGE_EXECUTED',
  PURGE_ERROR: 'PURGE_ERROR',
  RESIDENT_PURGE_APPROVED: 'RESIDENT_PURGE_APPROVED',
  RESIDENT_PURGE_REJECTED: 'RESIDENT_PURGE_REJECTED',
});

module.exports = { AUDIT_ACTIONS };
